export enum AUTH_TYPES {
 //? REGISTER
 REGISTER_SUCCESS = 'REGISTER_SUCCESS',
 REGISTER_FAIL = 'REGISTER_FAIL',

 //? LOGIN
 LOGIN_SUCCESS = 'LOGIN_SUCCESS',
 LOGIN_FAIL = 'LOGIN_FAIL',
 LOGOUT = 'LOGOUT',

 //? AUTH
 USER_LOADED = 'USER_LOADED',
 AUTH_ERROR = 'AUTH_ERROR',
 ACCOUNT_DELETED = 'ACCOUNT_DELETED',
 //?===================================================================
}
